# This is the Notebook use to implment the mathematical concepts which I learn related to ML 
<hr/>

In [1]:
import numpy as np

## Eigenvalues and Eigen vectors in Numpy

In [2]:
A = np.array([[2,-2,3],[1,1,1],[1,3,-1]])   # OUR MATRIX
A

array([[ 2, -2,  3],
       [ 1,  1,  1],
       [ 1,  3, -1]])

In [3]:
 # --> calculating eigen pairs

eig_values,eig_vectors = np.linalg.eig(A)

eig_values,eig_vectors

(array([ 3.,  1., -2.]),
 array([[ 0.57735027,  0.57735027, -0.61684937],
        [ 0.57735027, -0.57735027, -0.05607722],
        [ 0.57735027, -0.57735027,  0.78508102]]))