# This is the Notebook use to implment the mathematical concepts which I learn related to ML 
<hr/>

In [1]:
import numpy as np

## Eigenvalues and Eigen vectors in Numpy

In [2]:
A = np.array([[2,-2,3],[1,1,1],[1,3,-1]])   # OUR MATRIX
A

array([[ 2, -2,  3],
       [ 1,  1,  1],
       [ 1,  3, -1]])

In [4]:
 # --> calculating eigen pairs

eig_values,eig_vectors = np.linalg.eig(A)

eig_values

array([ 3.,  1., -2.])

In [5]:
eig_vectors
# each vector is arranged column wise.  i.e. => for λ1 = 3 , v1 = [0.5773 , 0.5773 , 0.5773]  (first element of each sub array)
# ? eigen vectros provided are of unit length

array([[ 0.57735027,  0.57735027, -0.61684937],
       [ 0.57735027, -0.57735027, -0.05607722],
       [ 0.57735027, -0.57735027,  0.78508102]])