# This is the Notebook use to implment the mathematical concepts which I learn related to ML 
---

In [2]:
import numpy as np

## Eigenvalues and Eigen vectors in Numpy

In [3]:
A = np.array([[2,-2,3],[1,1,1],[1,3,-1]])   # OUR MATRIX
A

array([[ 2, -2,  3],
       [ 1,  1,  1],
       [ 1,  3, -1]])

In [4]:
 # --> calculating eigen pairs

eig_values,eig_vectors = np.linalg.eig(A)

eig_values

array([ 3.,  1., -2.])

In [5]:
eig_vectors
# each vector is arranged column wise.  i.e. => for λ1 = 3 , v1 = [0.5773 , 0.5773 , 0.5773]  (first element of each sub array)
# ? eigen vectros provided are of unit length

array([[ 0.57735027,  0.57735027, -0.61684937],
       [ 0.57735027, -0.57735027, -0.05607722],
       [ 0.57735027, -0.57735027,  0.78508102]])

---
## Singualr Value Decomposition (SVD)

#### Normal mathematical way (without using python function) 

In [6]:
A = np.array([[4,11,14],[8,7,-2]])
A

array([[ 4, 11, 14],
       [ 8,  7, -2]])

In [7]:
 # --> SVD(A) = U Σ V

# Calculating U
U = np.linalg.eig(np.matmul(A,A.T))
U

EigResult(eigenvalues=array([360.,  90.]), eigenvectors=array([[ 0.9486833 , -0.31622777],
       [ 0.31622777,  0.9486833 ]]))

In [8]:
# Calculating V
V = np.linalg.eig(np.matmul(A.T,A))
V

EigResult(eigenvalues=array([ 3.60000000e+02, -1.91141861e-14,  9.00000000e+01]), eigenvectors=array([[-0.33333333, -0.66666667, -0.66666667],
       [-0.66666667,  0.66666667, -0.33333333],
       [-0.66666667, -0.33333333,  0.66666667]]))

In [9]:
np.linalg.matrix_rank(A)

2

In [10]:
singular_values = np.sqrt(V.eigenvalues)
singular_values

C:\Users\Dhyanesh Panchal\AppData\Local\Temp\ipykernel_17504\3355568677.py:1: RuntimeWarning: invalid value encountered in sqrt
  singular_values = np.sqrt(V.eigenvalues)


array([18.97366596,         nan,  9.48683298])

We can verify that UΣV = A

---
## SVD with inbuild functions  

In [11]:
np.set_printoptions(precision=4,suppress=True)

In [12]:
a = np.array([[1,2,3,4],[1,1,2,3],[0,1,1,0]]) # taking 4x3 matrix
a

array([[1, 2, 3, 4],
       [1, 1, 2, 3],
       [0, 1, 1, 0]])

In [13]:
# SVD of the matrix
# S is singular value array of 1D
U , S , V = np.linalg.svd(a,full_matrices=True)

In [14]:
U.shape , S.shape , V.shape

((3, 3), (3,), (4, 4))

In [15]:
U.__matmul__(U.T)   # itis orthogonal

array([[ 1.,  0.,  0.],
       [ 0.,  1., -0.],
       [ 0., -0.,  1.]])

In [19]:
# lest create sigma from S
b = np.diag(S)
sigma = np.zeros((3,4))
b

array([[6.7509, 0.    , 0.    ],
       [0.    , 1.1734, 0.    ],
       [0.    , 0.    , 0.2186]])

In [20]:
sigma[:,:-1] = b
sigma

array([[6.7509, 0.    , 0.    , 0.    ],
       [0.    , 1.1734, 0.    , 0.    ],
       [0.    , 0.    , 0.2186, 0.    ]])