# Introduction to SciKit-Learn


What is covered:

1. Scikit-learn Workflow
2. GEtting the Data ready
3. Choosing the right model/algorithm
4. Fitting the Data to the model
5. Evaluating the Model
6. Improving the Model


## 1. Scikit-learn Workflow

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## 2. Getting the Data

In [2]:

heart_disease = pd.read_csv('./sample_data/heart-disease.csv')
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [3]:
# --> Creating X (features Column)  and  Y(labels)

X = heart_disease.drop("target", axis=1)

y = heart_disease["target"]

## 3. Selecting the right model

In [4]:
# Using the random forest classifier
from sklearn.ensemble import RandomForestClassifier

In [5]:
clf = RandomForestClassifier()

# We will keep the default parameters
clf.get_params()  # These are hyper parameters

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

## 4. Fitting the Data

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2)  # test_size is 20%

In [8]:
clf.fit(X_train, y_train)

RandomForestClassifier()

In [9]:
X_test

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
3     56    1   1       120   236    0        1      178      0      0.8   
88    54    0   2       110   214    0        1      158      0      1.6   
10    54    1   0       140   239    0        1      160      0      1.2   
192   54    1   0       120   188    0        1      113      0      1.4   
55    52    1   1       134   201    0        1      158      0      0.8   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
20    59    1   0       135   234    0        1      161      0      0.5   
190   51    0   0       130   305    0        1      142      1      1.2   
188   50    1   2       140   233    0        1      163      0      0.6   
19    69    0   3       140   239    0        1      151      0      1.8   
56    48    1   0       122   222    0        0      186      0      0.0   

     slope  ca  thal  
3        2   0     2  
88       1   0     2  
10       2   0     2  
192      1   1     3  
55       2   1     2  
..     ...  ..   ...  
20       1   0     3  
190      1   0     3  
188      1   1     3  
19       2   2     2  
56       2   0     2  

[61 rows x 13 columns]

In [10]:
# make a prediction
y_pred = clf.predict(X_test)
y_pred

array([1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1], dtype=int64)

## 5. Evaluating the Data

In [11]:
clf.score(X_train, y_train)  # it will work perfect

1.0

In [12]:
clf.score(X_test, y_test)

0.8360655737704918

In [13]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [14]:
# --> Classification report
print(classification_report(y_pred=y_pred, y_true=y_test))

              precision    recall  f1-score   support

           0       0.77      0.83      0.80        24
           1       0.89      0.84      0.86        37

    accuracy                           0.84        61
   macro avg       0.83      0.84      0.83        61
weighted avg       0.84      0.84      0.84        61



In [15]:
# --> Confusion matrix
print(confusion_matrix(y_true=y_test, y_pred=y_pred))

[[20  4]
 [ 6 31]]


### 5. Improve the model

In [16]:
# Trying with different hyperparameters
best_n_estimator = 0
current_best_score = 0
for i in range(10, 100, 1):
    print(f"Trying thr model with {i}th estimator")
    clf = RandomForestClassifier(
        n_estimators=i
    )
    clf.fit(X_train, y_train)
    print(f"The Accuracy = {clf.score(X_test,y_test)}")
    if (clf.score(X_test, y_test) > current_best_score):
        current_best_score = clf.score(X_test, y_test)
        best_n_estimator = i

print(
    f"Best n_estimator is {best_n_estimator} with {current_best_score*100}% accuracy")

Trying thr model with 10th estimator
The Accuracy = 0.7540983606557377
Trying thr model with 11th estimator
The Accuracy = 0.8032786885245902
Trying thr model with 12th estimator
The Accuracy = 0.8032786885245902
Trying thr model with 13th estimator
The Accuracy = 0.8524590163934426
Trying thr model with 14th estimator
The Accuracy = 0.8360655737704918
Trying thr model with 15th estimator
The Accuracy = 0.8524590163934426
Trying thr model with 16th estimator
The Accuracy = 0.8360655737704918
Trying thr model with 17th estimator


The Accuracy = 0.819672131147541
Trying thr model with 18th estimator
The Accuracy = 0.8360655737704918
Trying thr model with 19th estimator
The Accuracy = 0.8360655737704918
Trying thr model with 20th estimator
The Accuracy = 0.8032786885245902
Trying thr model with 21th estimator
The Accuracy = 0.8032786885245902
Trying thr model with 22th estimator
The Accuracy = 0.7868852459016393
Trying thr model with 23th estimator
The Accuracy = 0.819672131147541
Trying thr model with 24th estimator
The Accuracy = 0.819672131147541
Trying thr model with 25th estimator
The Accuracy = 0.8032786885245902
Trying thr model with 26th estimator
The Accuracy = 0.819672131147541
Trying thr model with 27th estimator
The Accuracy = 0.8032786885245902
Trying thr model with 28th estimator
The Accuracy = 0.819672131147541
Trying thr model with 29th estimator
The Accuracy = 0.8852459016393442
Trying thr model with 30th estimator
The Accuracy = 0.819672131147541
Trying thr model with 31th estimator
The Accuracy

### 6. Saving the model

In [17]:
import pickle

pickle.dump(clf, open("first_model_random_forest.pkl", "wb"))

In [18]:
#  load the model

loaded_model = pickle.load(open("./first_model_random_forest.pkl", "rb"))

loaded_model.score(X_test, y_test)

0.8524590163934426

---
### 1. Getting the data ready

Three things:
1. Split the data into features (X) and labels (y)
2. Filling or disregarding missing values
3. Converting non-numericals to numerical

In [19]:
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [20]:
X = heart_disease.drop("target", axis=1)
X

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0     2  
3        2   0     2  
4        2   0     2  
..     ...  ..   ...  
298      1   0     3  
299      1   0     3  
300      1   2     3  
301      1   1     3  
302      1   1     2  

[303 rows x 13 columns]

In [21]:
y = heart_disease["target"]
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [22]:
# Splitting the data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_split = train_test_split(X, y, test_size=0.3)

#### This might be a good approach
> Clean Data  -->  Transform Data  -->  Reduce Data (column reduction)

### 1.1 Lets Transfer our data to numerics

In [23]:
car_sales = pd.read_csv("./sample_data/car-sales-extended.csv")
car_sales

Make Colour  Odometer (KM)  Doors  Price
0     Honda  White          35431      4  15323
1       BMW   Blue         192714      5  19943
2     Honda  White          84714      4  28343
3    Toyota  White         154365      4  13434
4    Nissan   Blue         181577      3  14043
..      ...    ...            ...    ...    ...
995  Toyota  Black          35820      4  32042
996  Nissan  White         155144      3   5716
997  Nissan   Blue          66604      4  31570
998   Honda  White         215883      4   4001
999  Toyota   Blue         248360      4  12732

[1000 rows x 5 columns]

In [24]:
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price             int64
dtype: object

In [25]:
# lets convert "Make" and "Colour" to numeric
X = car_sales.drop("Price", axis=1)
y = car_sales["Price"]
X, y

(       Make Colour  Odometer (KM)  Doors
 0     Honda  White          35431      4
 1       BMW   Blue         192714      5
 2     Honda  White          84714      4
 3    Toyota  White         154365      4
 4    Nissan   Blue         181577      3
 ..      ...    ...            ...    ...
 995  Toyota  Black          35820      4
 996  Nissan  White         155144      3
 997  Nissan   Blue          66604      4
 998   Honda  White         215883      4
 999  Toyota   Blue         248360      4
 
 [1000 rows x 4 columns],
 0      15323
 1      19943
 2      28343
 3      13434
 4      14043
        ...  
 995    32042
 996     5716
 997    31570
 998     4001
 999    12732
 Name: Price, Length: 1000, dtype: int64)

In [26]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# Listing the categorical features
categorical_features = ["Make" , "Colour" , "Doors"]

one_hot = OneHotEncoder()

transformer = ColumnTransformer([("one_hot",one_hot,categorical_features)],remainder="passthrough")

transformed_X = transformer.fit_transform(X)
transformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

One-Hot encoding Converts all the possible categories into individual columns 

In [27]:
pd.DataFrame(transformed_X)    # THe Odometer is not chnged but others are one hot encoded

0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

In [28]:
# Lets fit the model
np.random.seed(42)


X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3)